---
title: "Group Project"
author: "Katrina, Matina, Lindsey, Kaviya"
format: html
editor: visual
self-contained: true
---

```{r}
library(tidyverse)
library(janitor)


```

```{r}

# Load in the life expectancy csv
life_exp <-read_csv(here::here("life_expectancy_at_birth.csv"))

#load in the carbon emissions data 
carbon <-read_csv(here::here("co2_pcap_cons.csv"))

```

## DATA CLEANING

```{r}
#cleaning carbon
clean_carbon <- carbon %>% 
  na.omit() %>% 
  mutate(across(.cols = `2000`:`2022`, 
                .fns = ~as.numeric(.x))) %>% 
  select(country, `2000`:`2022`)

clean_life_exp <- life_exp %>% 
  na.omit() %>% 
  mutate(across(.cols = `2000`:`2022`, 
                .fns = ~as.numeric(.x))) %>% 
  select(country, `2000`:`2022`)

```

## Pivot the Data Longer:

```{r}
# Pivot longer the clean carbon data: 
clean_carbon <- clean_carbon %>%
  pivot_longer(cols = !country,
               names_to = "year",
               values_to = "carbon_emissions")


# Pivot longer the clean life expectancy data:
clean_life_exp <- clean_life_exp %>%
  pivot_longer(cols = !country,
               names_to = "year",
               values_to = "carbon_emissions")


```
